/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author LENOVO
 */
public class Minuman extends javax.swing.JFrame {

    /**
     * Creates new form Minuman
     */
    public Minuman() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab = new javax.swing.JTable();
        tnama = new javax.swing.JTextField();
        tha = new javax.swing.JTextField();
        bu = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        bi = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        bx = new javax.swing.JButton();
        cbka = new javax.swing.JComboBox<>();
        cbu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MINUMAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 94, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 134, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 214, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ukuran");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 254, -1, -1));

        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel2.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 142, -1));

        jtab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kategori", "Harga", "Ukuran"
            }
        ));
        jtab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtab);
        if (jtab.getColumnModel().getColumnCount() > 0) {
            jtab.getColumnModel().getColumn(0).setMaxWidth(50);
            jtab.getColumnModel().getColumn(1).setMinWidth(100);
            jtab.getColumnModel().getColumn(1).setMaxWidth(100);
            jtab.getColumnModel().getColumn(4).setMinWidth(50);
            jtab.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 351, 250));
        jPanel2.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 142, -1));
        jPanel2.add(tha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 142, -1));

        bu.setBackground(new java.awt.Color(204, 204, 255));
        bu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bu.setText("Update");
        bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buActionPerformed(evt);
            }
        });
        jPanel2.add(bu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        bd.setBackground(new java.awt.Color(204, 204, 255));
        bd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bd.setText("Delete");
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });
        jPanel2.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 70, -1));

        bi.setBackground(new java.awt.Color(204, 204, 255));
        bi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bi.setText("Insert");
        bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biActionPerformed(evt);
            }
        });
        jPanel2.add(bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, -1));

        bc.setBackground(new java.awt.Color(204, 204, 255));
        bc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bc.setText("Clear");
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });
        jPanel2.add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, -1));

        bx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bx.setForeground(new java.awt.Color(255, 0, 0));
        bx.setText("X");
        bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxActionPerformed(evt);
            }
        });
        jPanel2.add(bx, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 30));

        cbka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Teh", "Matcha", "Boba" }));
        jPanel2.add(cbka, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        cbu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        jPanel2.add(cbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jframe/pngtree-3d-render-of-the-interior-of-a-cozy-cafe-restaurant-image_3811953.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Harga");
        model.addColumn("Ukuran");

// load data dari DB
        try (
                Connection conn = Koneksi.getConnection(); 
                Statement st = conn.createStatement(); 
                ResultSet rs = st.executeQuery("SELECT * FROM dataminuman ORDER BY id_minuman")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_minuman"),
                    rs.getString("nama"),
                    rs.getString("kategori"),
                    rs.getInt("harga"),
                    rs.getString("ukuran")
                });
            }

            jtab.setModel(model); // tampilkan ke JTable
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }

    }


    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:
        tid.setText("");
        tnama.setText("");
        cbka.setSelectedIndex(0);
        tha.setText("");
        cbu.setSelectedIndex(0);

        tid.setEditable(true);
    }//GEN-LAST:event_bcActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:                                        
        try {
            String id = tid.getText();
            String sql = "DELETE FROM dataminuman WHERE id_minuman='" + id + "'";
            Connection conn = Koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

            // Refresh tabel
            tampilData();

            // Kosongkan textfield
            tid.setText("");
            tnama.setText("");
            cbka.setSelectedIndex(0);
            tha.setText("");
            cbu.setSelectedIndex(0);

            tid.setEditable(true);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bdActionPerformed

    private void biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tid.getText());
            String nama = tnama.getText();
            String kategori = cbka.getSelectedItem().toString();
            int harga = Integer.parseInt(tha.getText());
            String ukuran = cbu.getSelectedItem().toString();

            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO dataminuman (id_minuman, nama, kategori, harga, ukuran) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);
            ps.setString(2, nama);
            ps.setString(3, kategori);
            ps.setInt(4, harga);
            ps.setString(5, ukuran);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            
            tid.setText("");
            tnama.setText("");
            cbka.setSelectedIndex(0);
            tha.setText("");
            cbu.setSelectedIndex(0);

            tid.setEditable(true);   // Kosongkan textfield
            
            tampilData();
        } catch (NumberFormatException | SQLException e) {
            System.out.println("Gagal insert: " + e.getMessage());
        }
    }//GEN-LAST:event_biActionPerformed

    private void jtabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabMouseClicked
        // TODO add your handling code here:
        tid.setText(jtab.getValueAt(jtab.getSelectedRow(), 0).toString());
        tnama.setText(jtab.getValueAt(jtab.getSelectedRow(), 1).toString());
        cbka.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 2).toString());
        tha.setText(jtab.getValueAt(jtab.getSelectedRow(), 3).toString());
        cbu.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 4).toString());

        tid.setEditable(false);
    }//GEN-LAST:event_jtabMouseClicked

    private void buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE dataminuman SET nama = ?, kategori = ?, harga = ?, ukuran = ? WHERE id_minuman = ?";
            Connection conn = Koneksi.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);

            // Ambil dari textfield
            pst.setString(1, tnama.getText());
            pst.setString(2, cbka.getSelectedItem().toString());
            pst.setInt(3, Integer.parseInt(tha.getText()));
            pst.setString(4, cbu.getSelectedItem().toString());
            pst.setInt(5, Integer.parseInt(tid.getText())); // ID yang sudah auto increment

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

            // Refresh tabel
            tampilData();

            // Kosongkan textfield
            tid.setText("");
            tnama.setText("");
            cbka.setSelectedIndex(0);
            tha.setText("");
            cbu.setSelectedIndex(0);

            tid.setEditable(true);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buActionPerformed

    private void bxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bc;
    private javax.swing.JButton bd;
    private javax.swing.JButton bi;
    private javax.swing.JButton bu;
    private javax.swing.JButton bx;
    private javax.swing.JComboBox<String> cbka;
    private javax.swing.JComboBox<String> cbu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtab;
    private javax.swing.JTextField tha;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnama;
    // End of variables declaration//GEN-END:variables
}
